---
title: "new vs old WGS classifications"
author: "Austin Russell"
date: "2025-04-09"
output: html_document
---

adding the new WGS columns into the metadata 
```{r}
library(readxl)

# Read the entire sheet
data <- read_excel("/Users/russ/Desktop/Aim 1+2/aims 1+2 seq data/metadata.xlsx")

data <- data[!is.na(data$seq_file), ]

# Extract just one column by name
new_wgs <- data$new_wgs
three_wgs <- data$three_wgs

#add each new column
metadata$new_wgs <- new_wgs
metadata$three_wgs <- three_wgs


```


alpha comparisons of new wgs groupings 
```{r}

shannon_diversity<-estimate_richness(ps_nochloro, measures = "shannon")
inverse_simpson_index <- estimate_richness(ps_nochloro, measures = "InvSimpson")
chao1<- estimate_richness(ps_nochloro, measures = "Chao1")
richness<- estimate_richness(ps_nochloro, measures = "Observed")

# Calculate diversity measures
diversity_df <- data.frame(
  SampleID = sample_names(ps_nochloro),
  Shannon = estimate_richness(ps_nochloro, measures = "Shannon")[, "Shannon"],
  Chao = estimate_richness(ps_nochloro, measures = "Chao1")[, "Chao1"],
  Richness = estimate_richness(ps_nochloro, measures = "Observed")[, "Observed"],
  OTUs = otu_table(ps_nochloro) %>% rowSums()
)

#making the metadata object and confirming dataframes 
meta_data<-sample_data(ps_nochloro)
meta_data <- data.frame(as(meta_data, "matrix"))
diversity_df<-as.data.frame(diversity_df)

# Rename seq_file to SampleID in meta_data
colnames(meta_data)[colnames(meta_data) == "seq_file"] <- "SampleID"

# Combine with metadata
diversity_df <- merge(diversity_df, meta_data, by = "SampleID")

names(diversity_df)[names(diversity_df) == "X3_wgs"] <- "three_wgs"


# Filter out NAs
diversity_df <- diversity_df %>%
  filter(!is.na(wgs.class) & !is.na(collection_time) & !is.na(new_wgs) & !is.na(same_wgs) & !is.na(three_wgs))

# Set desired order for wgs.class and collection_time
desired_order_wgs <- c("BCCH", "HYCH", "ADV.CA", "CACH") 
diversity_df$wgs.class <- factor(diversity_df$wgs.class, levels = desired_order_wgs)
desired_order_collection_time <- c("initial", "self_feeding", "pre_surgery") 
diversity_df$collection_time <- factor(diversity_df$collection_time, levels = desired_order_collection_time)



#making sure the variables are seen as factors not characters 
diversity_df$wgs.class<-as.factor(diversity_df$wgs.class)
diversity_df$collection_time<-as.factor(diversity_df$collection_time)
diversity_df$Collection_year<-as.factor(diversity_df$Collection_year)
diversity_df$Sex<-as.factor(diversity_df$Sex)
diversity_df$Nest_Site<-as.factor(diversity_df$Nest_Site)
diversity_df$Nest<-as.factor(diversity_df$Nest)
diversity_df$new_wgs<-as.factor(diversity_df$new_wgs)
diversity_df$three_wgs<-as.factor(diversity_df$three_wgs)




#SHANNON DIVERSITY
#same
shan.old <- lmer(Shannon ~ wgs.class*collection_time*Sex + (1|Collection_year/Nest), data = diversity_df)
summary(shan.old)
#check the Anova 
Anova(shan.old)
#  model simplification
shan.old.ms <- update(shan.old, ~ . 
  - Sex:collection_time:wgs.class)
anova(shan.old.ms,shan.old)
Anova(shan.old.ms)
shan.old.ms.1 <- update(shan.old.ms, ~ . 
  - Sex:collection_time)
anova(shan.old.ms.1,shan.old.ms)
Anova(shan.old.ms.1)
shan.old.ms.2 <- update(shan.old.ms.1, ~ . 
  - Sex:wgs.class)
anova(shan.old.ms.1,shan.old.ms.2)
Anova(shan.old.ms.2)
shan.old.ms.3 <- update(shan.old.ms.2, ~ . 
  - collection_time:wgs.class)
anova(shan.old.ms.3,shan.old.ms.2)
Anova(shan.old.ms.3)




#new
shan.new <- lmer(Shannon ~ new_wgs*collection_time*Sex + (1|Collection_year/Nest), data = diversity_df)
summary(shan.new)
#check the Anova 
Anova(shan.new)
shan.new.ms <- update(shan.new, ~ . 
  - Sex:collection_time:new_wgs)
anova(shan.new.ms,shan.new)
Anova(shan.new.ms)
shan.new.ms.1 <- update(shan.new.ms, ~ . 
  - Sex:new_wgs)
anova(shan.new.ms.1,shan.new.ms)
Anova(shan.new.ms.1)
shan.new.ms.2 <- update(shan.new.ms.1, ~ . 
  - Sex:collection_time)
anova(shan.new.ms.1,shan.new.ms.2)
Anova(shan.new.ms.2)
shan.new.ms.3 <- update(shan.new.ms.2, ~ . 
  - new_wgs:collection_time)
anova(shan.new.ms.3,shan.new.ms.2)
Anova(shan.new.ms.3)





#three
shan.three <- lmer(Shannon ~ three_wgs*collection_time*Sex + (1|Collection_year/Nest), data = diversity_df)
summary(shan.three)
#check the Anova 
Anova(shan.three)
shan.three.ms <- update(shan.three, ~ . 
  - three_wgs:Sex:collection_time)
anova(shan.three.ms,shan.three)
Anova(shan.three.ms)
shan.three.ms.1 <- update(shan.three.ms, ~ . 
  - three_wgs:Sex)
anova(shan.three.ms.1,shan.three.ms)
Anova(shan.three.ms.1)
shan.three.ms.2 <- update(shan.three.ms.1, ~ . 
  - Sex:collection_time )
anova(shan.three.ms.1,shan.three.ms.2)
Anova(shan.three.ms.2)
shan.three.ms.3 <- update(shan.three.ms.2, ~ . 
  - three_wgs:collection_time )
anova(shan.three.ms.3,shan.three.ms.2)
Anova(shan.three.ms.3)





#CHAO DIVERSITY
#same
chao.old <- lmer(Chao ~ wgs.class*collection_time*Sex + (1|Collection_year/Nest), data = diversity_df)
summary(chao.old)
#check the Anova 
Anova(chao.old)



#new
chao.new <- lmer(Chao ~ new_wgs*collection_time*Sex + (1|Collection_year/Nest), data = diversity_df)
summary(chao.new)
#check the Anova 
Anova(chao.new)
chao.new.ms <- update(chao.new, ~ . 
  - new_wgs:Sex:collection_time)
anova(chao.new.ms,chao.new)
Anova(chao.new.ms)
chao.new.ms.1 <- update(chao.new.ms, ~ . 
  - Sex:collection_time)
anova(chao.new.ms,chao.new.ms.1)
Anova(chao.new.ms.1)
chao.new.ms.2 <- update(chao.new.ms.1, ~ . 
  - Sex:new_wgs)
anova(chao.new.ms.2,chao.new.ms.1)
Anova(chao.new.ms.2)
chao.new.ms.3 <- update(chao.new.ms.2, ~ . 
  - collection_time:new_wgs)
anova(chao.new.ms.2,chao.new.ms.3)
Anova(chao.new.ms.3)



#three
chao.three <- lmer(Chao ~ three_wgs*collection_time*Sex + (1|Collection_year/Nest), data = diversity_df)
summary(chao.three)
#check the Anova 
Anova(chao.three)
chao.three.ms <- update(chao.three, ~ . 
  - three_wgs:Sex:collection_time)
anova(chao.three.ms,chao.three)
Anova(chao.three.ms)
chao.three.ms.1 <- update(chao.three.ms, ~ . 
  - Sex:collection_time)
anova(chao.three.ms,chao.three.ms.1)
Anova(chao.three.ms.1)
chao.three.ms.2 <- update(chao.three.ms.1, ~ . 
  - Sex:three_wgs)
anova(chao.three.ms.2,chao.three.ms.1)
Anova(chao.three.ms.2)
chao.three.ms.3 <- update(chao.three.ms.2, ~ . 
  - collection_time:three_wgs)
anova(chao.three.ms.3,chao.three.ms.2)
Anova(chao.three.ms.3)


#NUMBER OF ASVs
#same
otu.old <- lmer(OTUs ~ same_wgs*collection_time*Sex + (1|Collection_year/Nest) + (1|Sex), data = diversity_df)
summary(otu.old)
#check the Anova 
Anova(otu.old)
otu.old.ms <- update(otu.old, ~ . 
  - same_wgs:Sex:collection_time)
anova(otu.old.ms,otu.old)
Anova(otu.old.ms)
otu.old.ms.1 <- update(otu.old.ms, ~ . 
  - Sex:collection_time)
anova(otu.old.ms,otu.old.ms.1)
Anova(otu.old.ms.1)
otu.old.ms.2 <- update(otu.old.ms, ~ . 
  - Sex:same_wgs)
anova(otu.old.ms.2,otu.old.ms.1)
Anova(otu.old.ms.2)
otu.old.ms.3 <- update(otu.old.ms.2, ~ . 
  - Sex:collection_time)
anova(otu.old.ms.3,otu.old.ms.2)
Anova(otu.old.ms.3)


#new
otu.new <- lmer(OTUs ~ new_wgs*collection_time*Sex + (1|Collection_year/Nest), data = diversity_df)
summary(otu.new)
#check the Anova 
Anova(otu.new)
otu.new.ms <- update(otu.new, ~ . 
  - new_wgs:Sex:collection_time)
anova(otu.new.ms,otu.new)
Anova(otu.new.ms)
otu.new.ms.1 <- update(otu.new.ms, ~ . 
  - Sex:collection_time)
anova(otu.new.ms,otu.new.ms.1)
Anova(otu.new.ms.1)
otu.new.ms.2 <- update(otu.new.ms.1, ~ . 
  - Sex:new_wgs)
anova(otu.new.ms.2,otu.new.ms.1)
Anova(otu.new.ms.2)


#three
otu.three <- lmer(OTUs ~ three_wgs*collection_time*Sex + (1|Collection_year/Nest), data = diversity_df)
summary(otu.three)
#check the Anova 
Anova(otu.three)
otu.three.ms <- update(otu.three, ~ . 
  - three_wgs:Sex:collection_time)
anova(otu.three.ms,otu.three)
Anova(otu.three.ms)
otu.three.ms.1 <- update(otu.three.ms, ~ . 
  - Sex:collection_time)
anova(otu.three.ms,otu.three.ms.1)
Anova(otu.three.ms.1)
otu.three.ms.2 <- update(otu.three.ms.1, ~ . 
  - Sex:three_wgs)
anova(otu.three.ms.2,otu.three.ms.1)
Anova(otu.three.ms.2)



```



beta comparisons of new wgs groupings 
```{r}

#PERMANOVA of beta diversity ordination plot 
library(vegan)

#set meta_data
meta_data<-sample_data(ps_nochloro)
meta_data <- data.frame(as(meta_data, "matrix"))

names(meta_data)[names(meta_data) == "X3_wgs"] <- "three_wgs"

# Bray-Curtis dissimilarity
bray <- phyloseq::distance(ps_nochloro, method = "bray")

# Jaccard dissimilarity
jaccard <- phyloseq::distance(ps_nochloro, method = "jaccard")


#perform PERMANOVA
permanova_result_old <- adonis2(jaccard  ~ wgs.class+Sex+collection_time, data = metadata, permutations = 10000, na.action = "na.exclude", by = "margin")
print(permanova_result_old)

permanova_result_new <- adonis2(jaccard ~ new_wgs+Sex+collection_time, data = metadata, permutations = 10000, na.action = "na.exclude", by = "margin")
print(permanova_result_new)

permanova_result_three <- adonis2(jaccard ~ three_wgs+Sex+collection_time, data = metadata, permutations = 10000, na.action = "na.exclude", by = "margin")
print(permanova_result_three)

```

remaking PCoA
```{r}
# Load necessary libraries
library(phyloseq)
library(ggplot2)

# Create distance matrix (Bray-Curtis)
dist_matrix <- phyloseq::distance(ps_nochloro, method = "bray")

# Perform PCoA
pcoa_result <- ordinate(ps_nochloro, method = "PCoA", distance = dist_matrix)


point_colors <- c("initial" = "", "self_feeding" = "", "pre_surgery" = "")
fill_colors <- c("BCCH" = "aquamarine3", "HYCH" = "chocolate1", "ADV.CA" = "cornflowerblue", "CACH" = "pink3")

# Create the PCoA plot
pcoa_plot <- plot_ordination(ps_nochloro, ordination, type = "samples") +
  geom_point(aes(shape = collection_time, color = Sex), size = 3) +  
  stat_ellipse(aes(group = Sex, fill = Sex, color = Sex),  # Add color to outline
               geom = "polygon", alpha = 0.2, size = 1) +  # Increase line size
  # scale_fill_manual(values = fill_colors) +
  # scale_color_manual(values = fill_colors) +
  theme_minimal() +
  labs(title = "PCoA of Microbial Communities",
       shape = "Collection Time", color = "Collection Time")


# Display the plot
print(pcoa_plot)


pdf(paste("/Users/russ/Desktop/pcoa_plot.pdf"), width = 10, height = 10)
print(pcoa_plot)
dev.off()


```

post hoc alpha - across new ancestry classifications 
```{r}

library(emmeans)
# checking post hoc after the linear mixed effects above 

emmeans_results <- emmeans(otu.new.ms.2, specs = "new_wgs", by = "collection_time")
# Get the estimated marginal means for the main effects and interactions
#emmeans_results <- emmeans(otu.three.ms.2, pairwise ~ collection_time*three_wgs)

# Perform pairwise comparisons (adjust method can be changed as needed)
contrast_results <- pairs(emmeans_results, adjust = "tukey")

# Print the results
summary(contrast_results)




# Visualize interaction while accounting for nesting
shan_emm<-emmip(otu.three.ms.2, ~ collection_time | three_wgs)
print(shan_emm)

# Save the plot to a PDF
pdf("/Users/russ/Desktop/shan_emm.pdf", width = 10, height = 5)
print(shan_emm)
dev.off()
print(shan_emm)


```

post hoc for the beta diversity testing 
```{r}
library(pairwiseAdonis)

# Bray-Curtis dissimilarity
bray <- phyloseq::distance(ps_nochloro, method = "bray")

# Jaccard dissimilarity
jaccard <- phyloseq::distance(ps_nochloro, method = "jaccard")

meta_data$three_wgs[meta_data$three_wgs == "N/A"] <- NA
meta_data$new_wgs[meta_data$new_wgs == "N/A"] <- NA
metadata$wgs.class[metadata$wgs.class == "N/A"] <- NA



#pairwise adonis
pairwise_result <- pairwise.adonis2(jaccard ~ wgs.class, data = meta_data, permutations = 9999, na.action = "na.exclude")
print(pairwise_result)

#the betadisper and tukey of betadisper shows how different the variance within groups is 
#Tukey HSD on betadisper: Tests group difference in within-group variability.
#If Tukey HSD is not significant → group dispersions are the same → PERMANOVA is likely reflecting real differences in composition.

# running the post hoc tests 
dispersion_test <- betadisper(bray, meta_data$wgs.class)
print(dispersion_test)

dispersion_result <- anova(dispersion_test)
print(dispersion_result)

pairwise_dispersion <- TukeyHSD(dispersion_test)
print(pairwise_dispersion)

```


looking for taxa related differences 
```{r}
#taxa relation to grouping differences in composition differences 
# Remove rows with NA values in the 'new_wgs' column
meta_data_clean <- sample_data(ps_nochloro)[!is.na(sample_data(ps_nochloro)$new_wgs), ]
# Subset OTU table based on the cleaned metadata
ps_clean <- prune_samples(rownames(meta_data_clean), ps_nochloro)
# Example: Run simper with the cleaned phyloseq object
otu_table_clean <- otu_table(ps_clean)
simper_result <- simper(otu_table_clean, group = sample_data(ps_clean)$new_wgs)
summary(simper_result)


```

line graph of hybrid index for each of the diff scales 
```{r}
library(ggplot2)

meta_data$hybrid.index <- as.numeric(meta_data$hybrid.index)


library(dplyr)

# Filter to unique band_id values
meta_data_unique <- meta_data %>% 
  distinct(band_id, .keep_all = TRUE)



new_wgs_line<-ggplot(meta_data_unique, aes(x = hybrid.index, y = 1, 
                      color = new_wgs, shape = new_wgs)) +
  geom_jitter(height = 0.05, width = 0, size = 3) +
  scale_x_continuous(limits = c(0, 1)) +
  theme_minimal() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  labs(title = "Samples Along the Hybrid Index",
       x = "Hybrid Index (0–1)",
       color = "WGS Class",
       shape = "WGS Class")


print(new_wgs_line)

pdf("/Users/russ/Desktop/new_wgs_line.pdf", width = 5, height = 5)
print(new_wgs_line)
dev.off()


old_wgs_line<-ggplot(meta_data_unique, aes(x = hybrid.index, y = 1, 
                      color = same_wgs, shape = same_wgs)) +
  geom_jitter(height = 0.05, width = 0, size = 3) +
  scale_x_continuous(limits = c(0, 1)) +
  theme_minimal() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  labs(title = "Samples Along the Hybrid Index",
       x = "Hybrid Index (0–1)",
       color = "WGS Class",
       shape = "WGS Class")

print(old_wgs_line)

pdf("/Users/russ/Desktop/old_wgs_line.pdf", width = 5, height = 5)
print(old_wgs_line)
dev.off()


three_wgs_line<-ggplot(meta_data_unique, aes(x = hybrid.index, y = 1, 
                      color = three_wgs, shape = three_wgs)) +
  geom_jitter(height = 0.05, width = 0, size = 3) +
  scale_x_continuous(limits = c(0, 1)) +
  theme_minimal() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  labs(title = "Samples Along the Hybrid Index",
       x = "Hybrid Index (0–1)",
       color = "WGS Class",
       shape = "WGS Class")

print(three_wgs_line)

pdf("/Users/russ/Desktop/three_wgs_line.pdf", width = 5, height = 5)
print(three_wgs_line)
dev.off()


```




